name: testes_unitarios
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  matcher: ^0.12.16
  http: ^1.1.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
